### ISSUE TITLE
Incomplete Toutnament API

### ISSUE THREAD

**Issue by adv0cat** [MingweiSamuel/Riven#14]
Hi, @MingweiSamuel !
This library does not support any requests other than GET requests.
In `tournament-v4` there are missing api:
- `POST /lol/tournament/v4/codes`
- `PUT /lol/tournament/v4/codes/{tournamentCode}`
- `POST /lol/tournament/v4/providers`
- `POST /lol/tournament/v4/tournaments`

In `tournament-stub-v4` there are missing api:
- ` POST /lol/tournament-stub/v4/codes `
- ` POST /lol/tournament-stub/v4/providers `
- ` POST /lol/tournament-stub/v4/tournaments `

Are you @MingweiSamuel planning to add missing api?
Or maybe I can help in their implementation? =)

**Comment by MingweiSamuel** [comment]
> Or maybe I can help in their implementation? =)

If you would like to that would be faster since I will be busy for a while :D.
Heres some places to get started:
- [RegionalRequester](https://github.com/MingweiSamuel/Riven/blob/02056f1e5983e6aa710014386904d1f13b17483e/src/req/regional_requester.rs#L67) would need to use the reqwest [request method](https://docs.rs/reqwest/0.10.6/reqwest/struct.Client.html#method.request) instead of get, take in the http verb as an argument, along with adding corresponding methods in RiotApi (keeping the current `.get` ones to preserve backwards compatibility).
- Need to [update the srcgen to handle all http verbs](https://github.com/MingweiSamuel/Riven/blob/02056f1e5983e6aa710014386904d1f13b17483e/srcgen/endpoints.rs.dt#L67-L69)
  - This could be a bit annoying since doT.js templates are very unforgiving

**Comment by MingweiSamuel** [comment]
Fixed in 40d49f837d98925b2b921c86961fe18b2d326eb3 for v2

**Comment by MingweiSamuel** [comment]
https://crates.io/crates/riven/2.0.0-beta.0

Example code: https://github.com/MingweiSamuel/Riven/blob/ad5b1c70ea1ea3e2d7d1c0af37b43b3640d73bd6/tests/tests_americas.rs#L19-L60
