### ISSUE TITLE
New gamemode

### ISSUE THREAD

**Issue by Kruptein** [MingweiSamuel/Riven#28]
A new gamemode "ultimate spellbook" is out.

```
RiotApiError {
    reqwest_error: reqwest::Error {
        kind: Decode, source: Error("invalid value: 1400, expected one of: 0, 2, 4, 6, 7, 8, 9, 14, 16, 17, 25, 31, 32, 33, 41, 42, 52, 61, 65, 67, 70, 72, 73, 75, 76, 78, 83, 91, 92, 93, 96, 98, 100, 300, 310, 313, 315, 317, 318, 325, 400, 410, 420, 430, 440, 450, 460, 470, 600, 610, 700, 800, 810, 820, 830, 840, 850, 900, 910, 920, 940, 950, 960, 980, 990, 1000, 1010, 1020, 1030, 1040, 1050, 1060, 1070, 1090, 1100, 1110, 1111, 1200, 1300, 2000, 2010, 2020", line: 1, column: 80)
    },
    retries: 0, response: None, status_code: Some(200)
}
```

**Comment by MingweiSamuel** [comment]
https://github.com/RiotGames/developer-relations/issues/507

**Comment by MingweiSamuel** [comment]
Fixed in https://crates.io/crates/riven/1.13.3

(On another note this sort of thing won't be a problem in v2 because we've switched to newtype-based enums which can handle unknown values)

**Comment by Kruptein** [comment]
bless :pray: I wasn't aware there was a v2, is it stable enough to use already?

**Comment by MingweiSamuel** [comment]
Yeah there is `2.0.0-beta.3` though "beta" is a bit wrong since there'll probably still be a few more breaking changes in the library api.

It's not too too different, it has
* the [newtype-based enums](https://docs.rs/riven/2.0.0-beta.3/riven/consts/struct.Queue.html)
* separate region enums for different endpoint [renamed to Routes](https://docs.rs/riven/2.0.0-beta.3/riven/consts/enum.Route.html#variant.Platform)
* tracing support (on branch, not published just yet)
* a few small performance improvements.

If you want to try it I welcome any feedback or change suggestions before it fully stabilizes
